+ module purge
+ '[' purge == load ']'
++ /usr/bin/modulecmd bash purge
+ eval
+ '[' purge == load ']'
+ module load anaconda/py3
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load anaconda/py3
                                                                 
                                                                                
##############################################                                  
INFORMATION                                                                     
##############################################                                  
                                                                                
You have loaded the base anaconda environment. For specialized environments,    
you must first enable them with `source activate [env]`.                        
                                                                                
For a full list of environments, type `conda env list`                          
  
+ eval INCLUDE=/packages/7x/anaconda3/5.3.0/include ';export' 'INCLUDE;INFOPATH=/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3' ';export' '_LMFILES_;unset' 'MODULEBUILDRC;unset' 'PERL5LIB;unset' 'PERL_LOCAL_LIB_ROOT;unset' 'PERL_MB_OPT;unset' 'PERL_MM_OPT;'
++ INCLUDE=/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ LD_LIBRARY_PATH=/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3
++ export LOADEDMODULES
++ MANPATH=/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3
++ export _LMFILES_
++ unset MODULEBUILDRC
++ unset PERL5LIB
++ unset PERL_LOCAL_LIB_ROOT
++ unset PERL_MB_OPT
++ unset PERL_MM_OPT
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ cut '-d ' -f1
+ tail -n +3
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ sed 's/^+ //'
+ grep --color=auto '^+'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load anaconda/py3
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ module load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
++ /usr/bin/modulecmd bash load hdf5/1.10.1-gnu-stock-openmpi-3.0.0


##############################################
INFORMATION
##############################################

OpenMPI uses mpirun or mpiexec by default.

To use srun, you must include the --mpi=pmi2 option.

(e.g. srun --mpi=pmi2 ./executable)

See the manpages for mpirun and srun for more
information (e.g. man srun).


+ eval HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock ';export' 'HDF5_DIR;INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include' ';export' 'INCLUDE;INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info' ';export' 'INFOPATH;JAVA_HOME=/packages/7x/java/8u162' ';export' 'JAVA_HOME;LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib' ';export' 'LD_LIBRARY_PATH;LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' 'LOADEDMODULES;MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man' ';export' 'MANPATH;PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin' ';export' 'PATH;ZLIBCFLAGS=\' -I/packages/7x/zlib/1.2.8/include ';export' 'ZLIBCFLAGS;ZLIBLDFLAGS=\' -L/packages/7x/zlib/1.2.8/lib ';export' 'ZLIBLDFLAGS;_LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0' ';export' '_LMFILES_;'
++ HDF5_DIR=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock
++ export HDF5_DIR
++ INCLUDE=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/include:/packages/7x/szip/2.1/include:/packages/7x/zlib/1.2.8/include:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/include:/packages/7x/hwloc/1.11.8/include:/packages/7x/anaconda3/5.3.0/include
++ export INCLUDE
++ INFOPATH=/packages/7x/zlib/1.2.8/share/info:/packages/7x/anaconda3/5.3.0/share/info
++ export INFOPATH
++ JAVA_HOME=/packages/7x/java/8u162
++ export JAVA_HOME
++ LD_LIBRARY_PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/lib:/packages/7x/szip/2.1/lib:/packages/7x/zlib/1.2.8/lib:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/lib:/packages/7x/hwloc/1.11.8/lib:/packages/7x/anaconda3/5.3.0/lib
++ export LD_LIBRARY_PATH
++ LOADEDMODULES=anaconda/py3:java/latest:hwloc/1.11.8:openmpi/3.0.0-gnu-stock:zlib/1.2.8:szip/2.1:hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export LOADEDMODULES
++ MANPATH=/packages/7x/zlib/1.2.8/share/man:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/share/man:/packages/7x/hwloc/1.11.8/share/man:/packages/7x/java/8u162/man:/packages/7x/anaconda3/5.3.0/share/man:/usr/share/man:/usr/local/share/man
++ export MANPATH
++ PATH=/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
++ ZLIBCFLAGS=' -I/packages/7x/zlib/1.2.8/include'
++ export ZLIBCFLAGS
++ ZLIBLDFLAGS=' -L/packages/7x/zlib/1.2.8/lib'
++ export ZLIBLDFLAGS
++ _LMFILES_=/usr/share/Modules/modulefiles/anaconda/py3:/usr/share/Modules/modulefiles/java/latest:/usr/share/Modules/modulefiles/hwloc/1.11.8:/usr/share/Modules/modulefiles/openmpi/3.0.0-gnu-stock:/usr/share/Modules/modulefiles/zlib/1.2.8:/usr/share/Modules/modulefiles/szip/2.1:/usr/share/Modules/modulefiles/hdf5/1.10.1-gnu-stock-openmpi-3.0.0
++ export _LMFILES_
+ '[' load == load ']'
+ /usr/bin/modulecmd bash list -l
+ tail -n +3
+ cut '-d ' -f1
+ diff -c /tmp/ejakupov-prelist /tmp/ejakupov-postlist
+ grep --color=auto '^+'
+ sed 's/^+ //'
++ cat /tmp/ejakupov-difflist
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load java/latest
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hwloc/1.11.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load openmpi/3.0.0-gnu-stock
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load zlib/1.2.8
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load szip/2.1
+ for bobsyeruncle_module_xxx in '$(cat /tmp/${USER}-difflist)'
+ /packages/sysadmin/environment_modules/database/module_db.py load hdf5/1.10.1-gnu-stock-openmpi-3.0.0
+ /bin/rm -f /tmp/ejakupov-prelist
+ /bin/rm -f /tmp/ejakupov-postlist
+ /bin/rm -f /tmp/ejakupov-difflist
+ /packages/sysadmin/slurm_scripts/module.py
+ source activate mda2
++ _CONDA_ROOT=/packages/7x/anaconda3/5.3.0
++ . /packages/7x/anaconda3/5.3.0/etc/profile.d/conda.sh
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ '[' -z '' ']'
+++ export CONDA_SHLVL=0
+++ CONDA_SHLVL=0
+++ '[' -n x ']'
+++ '[' -n '' ']'
+++++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++++ dirname /packages/7x/anaconda3/5.3.0/bin
+++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export PATH
+++ '[' -z '' ']'
+++ PS1=
++ conda activate mda2
++ '[' 2 -lt 1 ']'
++ local cmd=activate
++ shift
++ case "$cmd" in
++ __conda_activate activate mda2
++ '[' -n '' ']'
++ local cmd=activate
++ shift
++ local ask_conda
++ OLDPATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ __add_sys_prefix_to_path
++ '[' -n '' ']'
+++ dirname /packages/7x/anaconda3/5.3.0/bin/conda
++ SYSP=/packages/7x/anaconda3/5.3.0/bin
+++ dirname /packages/7x/anaconda3/5.3.0/bin
++ SYSP=/packages/7x/anaconda3/5.3.0
++ '[' -n '' ']'
++ PATH=/packages/7x/anaconda3/5.3.0/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ export PATH
+++ PS1=
+++ /packages/7x/anaconda3/5.3.0/bin/conda shell.posix activate mda2
++ ask_conda='PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
++ PATH=/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts/:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
++ eval 'PS1='\''(mda2) '\''
export PATH='\''/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin'\''
export CONDA_PREFIX='\''/home/ejakupov/.conda/envs/mda2'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''mda2'\''
export CONDA_PROMPT_MODIFIER='\''(mda2) '\''
export CONDA_EXE='\''/packages/7x/anaconda3/5.3.0/bin/conda'\''
export _CE_M='\'''\''
export _CE_CONDA='\'''\''
export CONDA_PYTHON_EXE='\''/packages/7x/anaconda3/5.3.0/bin/python'\'''
+++ PS1='(mda2) '
+++ export PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ PATH=/home/ejakupov/.conda/envs/mda2/bin:/packages/7x/anaconda3/5.3.0/condabin:/packages/7x/hdf5/1.10.1/openmpi/3.0.0/gcc/stock/bin:/packages/7x/openmpi/agave/3.0.0/gcc/stock/normal/bin:/packages/7x/hwloc/1.11.8/bin:/packages/7x/java/8u162/bin:/packages/7x/anaconda3/5.3.0/bin:/usr/lib64/qt-3.3/bin:/home/ejakupov/perl5/bin:/packages/scripts:/packages/sysadmin/agave/scripts:/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/packages/7x/perl5lib/bin:/home/ejakupov/.local/bin:/home/ejakupov/bin
+++ export CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ CONDA_PREFIX=/home/ejakupov/.conda/envs/mda2
+++ export CONDA_SHLVL=1
+++ CONDA_SHLVL=1
+++ export CONDA_DEFAULT_ENV=mda2
+++ CONDA_DEFAULT_ENV=mda2
+++ export 'CONDA_PROMPT_MODIFIER=(mda2) '
+++ CONDA_PROMPT_MODIFIER='(mda2) '
+++ export CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ CONDA_EXE=/packages/7x/anaconda3/5.3.0/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
+++ CONDA_PYTHON_EXE=/packages/7x/anaconda3/5.3.0/bin/python
++ __conda_hashr
++ '[' -n '' ']'
++ '[' -n '' ']'
++ hash -r
+ testdir=/scratch/ejakupov/Agave/temp/7496329
+ export OMP_NUM_THREADS=1
+ OMP_NUM_THREADS=1
+ mpiexec -n 112 python -W ignore /scratch/ejakupov/Agave/benchmarks/h5py/scripts/benchmark.py /scratch/ejakupov/Agave/temp/7496329/YiiP_system.pdb /scratch/ejakupov/Agave/temp/7496329/YiiP_system_9ns_center100x.h5md run5/4node_3
Exception ignored in: <function ReaderBase.__del__ at 0x2b6d349668b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2acdead668b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b537c0f88b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aab42ee18b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba283dfa8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b560236f8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b6bbc3f48b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aca73b358b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b4ad0f968b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad13bf7f8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae0834a28b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b27f26648b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b6a7429c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba6a3edc8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aff2f4f98b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b6f789758b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2af08260d8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9aee30a8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b0edff9c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b5ebee558b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b357478a8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b8de31718b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2abecf09f8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b02ceb978b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b82765448b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b10cbfff8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b2e78ba38b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b87cdfe78b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b69466178b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba0583568b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aab866468b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ab6415d48b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ab4898978b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b8e65bdd8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9049d598b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b8e94d278b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b0f596608b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2acbaf0c78b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2af0e10958b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aeac31eb8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b7625fc58b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b997f68c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1b749be8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1e4cb528b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1f9130f8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aced866c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b3a080ce8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b4d380608b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2af62a2da8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b74839538b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ac2ff6768b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2af7cbba18b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b30439f38b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba1640118b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b81b30028b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b5cf85f68b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba1a970d8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ab01a6e18b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b4f38ab58b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b15f2e328b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b31a902c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b4ac75778b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b79e7d668b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae484bac8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2affa6b398b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b3f2b14b8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae63d3758b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b2e8e7a38b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aed64cea8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9e8c5c68b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b7f5b4d48b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b9c29ae98b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b21736b98b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b87362be8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2afc7a7328b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b162f3988b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b619f7b48b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b30bd58c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b6f89b618b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ab49a4028b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b398678c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b52997728b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1f640c28b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b40bf1448b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad44ca148b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b705c0c58b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b24883938b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b7f7180c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b800f7188b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b47c85d78b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b83072b08b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2aeb904048b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b7dba17d8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ae70abb18b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b807d8108b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad4eaee68b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b1e3498a8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b500a4e48b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b53101de8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ad40ac308b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b15911128b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2adab7d1b8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b98070358b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2acd3c1738b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ac721cff8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b8f884ec8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b84a8f078b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b51a28e38b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b99967b18b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2b322296c8b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function ReaderBase.__del__ at 0x2ba4e4c718b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
Traceback (most recent call last):
  File "/scratch/ejakupov/Agave/benchmarks/h5py/scripts/benchmark.py", line 218, in <module>
    df = pd.DataFrame(times_array, columns=columns)
NameError: name 'pd' is not defined
Exception ignored in: <function ReaderBase.__del__ at 0x2acdf94c98b0>
Traceback (most recent call last):
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/base.py", line 2161, in __del__
  File "/home/ejakupov/mdanalysis/package/MDAnalysis/coordinates/H5MD.py", line 781, in close
  File "/home/ejakupov/.conda/envs/mda2/lib/python3.8/site-packages/h5py-2.9.0-py3.8-linux-x86_64.egg/h5py/_hl/files.py", line 412, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 264, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 43, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[7378,1],0]
  Exit code:    1
--------------------------------------------------------------------------
+ rm -r /scratch/ejakupov/Agave/temp/7496329
